
version: '3'
services:
  server:
    container_name: pyQSM
    devices:
      - "/dev/dri:/dev/dri" 
    build: .
    deploy:
        resources:
            limits:
                cpus: '3.5'
                memory: 7.5gb
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
