
version: '3'
services:
  py-qsm:
    container_name: pyQSM
    devices:
      - "/dev/dri/card0:/dev/dri/card0" 
    build: ./py_qsm
    deploy:
        resources:
            limits:
                cpus: '1'
                memory: 2gb
    ports:
      - '5000:5000'
      - '81:5000'
    volumes:
      - ./py_qsm:/py_qsm
      - /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY
    hostname: py-qsm
    #links:
    #  - 'o3d-rtc:rtc'
  
  stl:
    container_name: stl
    build: ./stl
    deploy:
        resources:
            limits:
                cpus: '2'
                memory: 6gb
    ports:
      - '5001:5001'
      - '82:5001'
    #environment:
    #  PYTHONHOME: /from-host
    #  PYTHONPATH: /usr/local/lib/python3.8:/usr/local/lib/python3.8/lib-dynload:/from-host/lib/python3.8/site-packages \
    volumes:
      - ./stl:/stl
      - /tmp/.X11-unix:/tmp/.X11-unix
    #extra-hosts:
    #  - "host.docker.internal:host-gateway"
    #network_mode: host
      #- type: bind
      #  source: /home/wischmcj/Desktop/pyQSM/venv/bin/
      #  target: /from-host
    hostname: stl

#  o3d-rtc:
#    container_name: o3dRTC
#    devices:
#      - "/dev/dri/card0:/dev/dri/card0"
#    build: ./o3d_rtc
#    deploy:
#        resources:
#            limits:
#                cpus: '2'
#                memory: 5gb
#    ports:
#      - "5002:5002"
#      - "82:5002"
#    volumes:
#      - ./o3d_rtc:/o3d_rtc/
#      - /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY
      #- /home/wischmcj/Desktop/open3d-headless-docker:/root
#    hostname: o3d-rtc
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    #networks:
    #  - rtc-net
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - '80:80'
    #networks:
    #- rtc-net
    depends_on:
    - py-qsm
    - stl
    extra_hosts: 
      - "host.docker.internal:host-gateway"

