
[initial_clean]
voxel_size = 0.02
neighbors = 6
ratio = 4
iters = 3

[stem]
normals_radius = 0.1
normals_nn = 30
angle_cutoff = 10
stem_voxel_size = 0.03
post_id_stat_down = true
stem_neighbors = 10
stem_ratio = 2
stem_iters = 3

[trunk]
num_lowest = 2000
trunk_neighbors = 10
trunk_ratio = 0.25

[dbscan]
epsilon = 0.1
min_neighbors = 10

[sphere]
min_radius = 0.01
max_radius = 1.5
radius_multiplier = 1.75
dist = 0.07
bad_fit_radius_factor = 2.5
min_contained_points = 8

